media_entity.bundle.type.svg_icon:
  type: mapping
  label: 'SVG icon type configuration'
  mapping:
    source_field:
      type: string
      label: 'Field with SVG sprite'
    id_field:
      type: string
      label: 'Field with ID information'

media_entity.bundle.type.svg_sprite:
  type: mapping
  label: 'SVG sprite type configuration'
  mapping:
    svg_field:
      type: string
      label: 'SVG sprite field'
    target_bundle:
      type: string
      label: 'Target SVG icon bundle'
    autocreate_icons:
      type: boolean
      label: 'Create icons automatically'
    autocreate_triggers:
      type: mapping
      label: 'Autocreate triggers'
      mapping:
        insert:
          type: string
          label: 'Create icons for a new sprite'
        update:
          type: string
          label: 'Create missing icons on sprite update'

field.formatter.settings.video_embed_field_thumbnail:
  type: mapping
  label: 'Thumbnail formatter settings.'
  mapping:
    wrap:
      type: boolean
      label: 'Add wrapper to icon'
    wrap_classes:
      type: string
      label: 'Wrapper classes'
    icon_classes:
      type: string
      label: 'Icon classes'
    icon_classes:
      type: string
      label: 'Icon classes'
